version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - fastapi_streamlit_network
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    environment:
      - APP_SETTINGS=development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - fastapi_streamlit_network
    ports:
      - 8501:8501
    volumes:
      - ./frontend:/app
    environment:
      BACKEND_HOST: backend:8000
    depends_on:
      - backend
networks:
  fastapi_streamlit_network:
    driver: bridge
